import matplotlib

ANALYSIS_SPECIMEN = ["BA38",
                     "BA37",
                     "BA36",
                     "AD77",
                     "AD76",
                     "AD68",
                     "AD67",
                     "AD66",
                     "AD64",
                     "AD63",
                     "AD52",
                     "AD51",
                     "AD50",
                     "AD48",
                     "AD45",
                     "AD43",
                     "AD42",
                     "AD40",
                     "AD38",
                     "AD36",
                     "AD33",
                     "AD32",
                     "AD31",
                     "AD29",
                     "AD28",
                     "AD21",
                     "AD20",
                     "AD19",
                     "AD18",
                     "AD17",
                     "AD16",
                     "AD14",
                     "AD12",
                     "AC15",
                     "AC11",
                     "AC14",
                     "BA07",
                     "BA05"]

CMAP_MASK = matplotlib.colors.ListedColormap(((1, 1, 0.6),
                                              (0.2, 1, 1),
                                              (0.627, 0.627, 0.627)
                                              ))
